replicaCount: 1

image:
  repository: registry.iprogrammer.uz/botspace/websocket
  tag: "0577099"
  pullPolicy: Always

imagePullSecrets:
  - name: iprogrammer-registry

fullnameOverride: "websocket"

serviceAccount:
  create: false
  name: ""

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080

# References to EXISTING secrets NOT managed by this chart
envFrom:
  - secretRef:
      name: redis-secret

env:
  - name: PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        name: jwt-secret
        key: PUBLIC_KEY

probes:
  startup:
    enabled: true
    type: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 12
  readiness:
    enabled: true
    type: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  liveness:
    enabled: true
    type: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi

prometheus:
  scrape: true
  port: 8080

terminationGracePeriodSeconds: 30
